package com.br.common.bean;

public enum ServiceName {
	CORE_SERVICE,
	DAC_SERVICE,
	FRAUD_SERVICE,
	AL_SERVICE,
	SL_SERVICE,
	RULE_SERVICE,
	SCORE_SERVICE,
	MEDUSA_SERVICE,
	DECISION_SERVICE
}
